### PR TITLE
脚本添加

### PR DESCRIPTION
**Pull request by wy3057**
feat(repo): 添加多个游戏辅助脚本

- 新增切换角色脚本（1号至4号角色）
- 新增前后左右行走脚本（5秒）
- 新增进入尘歌壶脚本
- 新增领取洞天宝钱和好感脚本
- 新增稻妻合成台脚本
- 新增尘歌壶内不同地点找阿圆脚本
This pull request includes several updates to the `repo.json` file and the addition of new scripts for various character actions in the `repo/js` directory. The most important changes include updates to the repository metadata, the addition of new character action scripts, and their corresponding manifest files.

### Repository Metadata Updates:
* [`repo.json`](diffhunk://#diff-a630562e11654eb1c535423ca16dfc55fbe974225dc07f0d34fc105a86aa5fc4L2-R2): Updated the timestamp and added new entries for various character actions and descriptions. [[1]](diffhunk://#diff-a630562e11654eb1c535423ca16dfc55fbe974225dc07f0d34fc105a86aa5fc4L2-R2) [[2]](diffhunk://#diff-a630562e11654eb1c535423ca16dfc55fbe974225dc07f0d34fc105a86aa5fc4R4613-R4742)

### New Character Action Scripts:
* [`repo/js/切换1号角色/main.js`](diffhunk://#diff-396a106c17cdb7e5e35da53ed1bfb6a10737f2704b81225c665c02ec758ab658R1-R6): Added script to switch to character 1.
* [`repo/js/切换2号角色/main.js`](diffhunk://#diff-c01c34b869372850460babe5ec1efc9ecfd3c92b88fc07def66451a331f2ecc9R1-R6): Added script to switch to character 2.
* [`repo/js/切换3号角色/main.js`](diffhunk://#diff-e2fcd0fcaa40a262275986b5c5b0c66d70c12d00a31a6fcd34607a16c9063b6eR1-R6): Added script to switch to character 3.
* [`repo/js/切换4号角色/main.js`](diffhunk://#diff-2fb635e26146ed59b24c81528c29506c0eca9b8a5bdca1c80c16e6e1d1452bdbR1-R6): Added script to switch to character 4.
* [`repo/js/向前行走5秒/main.js`](diffhunk://#diff-a7f808c726a88ec65ca0813d06796dfd02695bb519914b2d267cc27e7743f75fR1-R9): Added script to walk forward for 5 seconds.
* [`repo/js/向右行走5秒/main.js`](diffhunk://#diff-98781ca9f0d8cd5843b5fb0043b83a9db1fdc4181e763ba902e181ca0ec37590R1-R9): Added script to walk right for 5 seconds.
* [`repo/js/向后行走5秒/main.js`](diffhunk://#diff-5a298dcc42bc3958a043c84bc9e36ae119ab7dc68386f131d1dc91367c3ad29bR1-R9): Added script to walk backward for 5 seconds.
* [`repo/js/向左行走5秒/main.js`](diffhunk://#diff-9cf7a6a2e9d231442e88ba5a3382080f5365b7b896753f883cd090f8ef5fbe82R1-R9): Added script to walk left for 5 seconds.
* [`repo/js/尘歌壶妙香林找阿圆/尘歌壶妙香林找阿圆/main.js`](diffhunk://#diff-53d7412e5dad6b4c54fed16a03f93ddb1e8d561b4602ae6505ef447c18f40b58R1-R9): Added script to walk right for 1.5 seconds to find 阿圆.
* [`repo/js/尘歌壶清琼岛找阿圆/main.js`](diffhunk://#diff-140ded0e826407e0b6ac4ab454d82743f710abcf4c33f610e64128f5aa0629dfR1-R9): Added script to walk left for 1.5 seconds to find 阿圆.

### New Manifest Files:
* [`repo/js/切换1号角色/manifest.json`](diffhunk://#diff-014e71c5cba8a8ce7f4c03c03fdad08934218b0760bdf2e89b04060d405a6895R1-R12): Added manifest for switching to character 1.
* [`repo/js/切换2号角色/manifest.json`](diffhunk://#diff-13262e577569a965b9d6c61559560e0f43a200c8ceba5e64a937eab58fa7e270R1-R12): Added manifest for switching to character 2.
* [`repo/js/切换3号角色/manifest.json`](diffhunk://#diff-ca8653d26e8899c2e3337532ab40ad36b00f8609564a478539f3c030073c96e2R1-R12): Added manifest for switching to character 3.
* [`repo/js/切换4号角色/manifest.json`](diffhunk://#diff-e9f4f5b06c94bbf44021b8a09d0be3f50e86383806c9a9b0592541bbad8472c7R1-R12): Added manifest for switching to character 4.
* [`repo/js/向前行走5秒/manifest.json`](diffhunk://#diff-3581db4ad7a1f5bce9ad0f271ee17a71fe56b3999908fe46387e8470947fd020R1-R12): Added manifest for walking forward for 5 seconds.
* [`repo/js/向右行走5秒/manifest.json`](diffhunk://#diff-d25eadeb6c837ab33aaeb56a6d987e350061703ac0790a63f301a3fa3db7b3b7R1-R12): Added manifest for walking right for 5 seconds.
* [`repo/js/向后行走5秒/manifest.json`](diffhunk://#diff-eeaeda6c97c5f84bff93c30e5c237e3f6f8ce6797f4e82d1eb23fca83af4eac0R1-R12): Added manifest for walking backward for 5 seconds.
* [`repo/js/向左行走5秒/manifest.json`](diffhunk://#diff-1d2d498cd91942b2428f3822a59aaa08e3cae3d641df3b5f7d8c260ffe6bf779R1-R12): Added manifest for walking left for 5 seconds.
* [`repo/js/尘歌壶妙香林找阿圆/尘歌壶妙香林找阿圆/manifest.json`](diffhunk://#diff-99b0274bdce4f536f7390a32358c9032952a850363651b2fb1f882d9baab38d5R1-R12): Added manifest for walking right for 1.5 seconds to find 阿圆.

### CODE REVIEW

**Comment by huiyadanli** [comment]
image

这个文件夹有问题

**Comment by wy3057** [comment]
看到了，正在改

**Comment by wy3057** [comment]
现在应该好了

**Comment by huiyadanli** [comment]
image

.idea 目录 要删下

**Comment by wy3057** [comment]
刚刚手贱了，现在好了
13ca6af3f89052417a9ecbd64f1ec60f

**Comment by huiyadanli** [comment]
这图真高清

**Comment by wy3057** [comment]
包的

**Comment by huiyadanli** [comment]
@jhkif 已上传

**Comment by wy3057** [comment]
艹了，我用变基更新本地仓库把文件全更没了
e16451069015af184bee095e1ad33c8f

**Comment by huiyadanli** [comment]
强制以远端为准，reset过去然后pull就好了

**Comment by huiyadanli** [comment]
image

这几个前进的name实际都是描述，顺便把文件名作为name吧

**Comment by wy3057** [comment]
就这样吧

**Comment by wy3057** [comment]
我睡觉去了，下午还要上课
7e066deb9b85094216411b43098ca4a2

**Pull request merged**
